### ISSUE TITLE
Update to `Fable.Browser.Url 1.3` causes compilation error

### ISSUE THREAD

**Issue by lukaszkrzywizna** [fable-compiler/fable-browser#116]
Hi, 

After an update of `Fable.Browser.Url` from 1.2 --> 1.3 I've started to receive an error:

```fsharp
FSC: Error FS0193 : The module/namespace 'Types' from compilation unit 'Browser.Url' did not contain the val 'ValLinkagePartialKey(Create)'
```

Do you have any idea what can cause a problem? I assume that this can be somehow correlated to this PR: #115

**Comment by MangelMaxime** [comment]
Hello,

we are again being bitten by F#/.NET which consider that it can't find/use the new method even if it is compatible with previous code...

I released a new version of the library can you please give it a try and see if that solve your issue?

If it doesn't can you please try to identify which of your dependencies depends on `Fable.Browser.Url` so I can ask the maintainer to re compile it.

**Comment by lukaszkrzywizna** [comment]
Good news - it works!

I must admit, I would never expect that this kind of change would cause any problems—especially those hard to track and identify. 

I've only one package using `Fable.Browser.Url` as a dependency -  [Elmish.Bridge.Client](https://github.com/Nhowka/Elmish.Bridge) and I assume that this one should be rebuilt.

**Comment by MangelMaxime** [comment]
> I've only one package using Fable.Browser.Url as a dependency - [Elmish.Bridge.Client](https://github.com/Nhowka/Elmish.Bridge) and I assume that this one should be rebuilt.

So the new version 1.3.1 didn't fix your problem?

I am asking because if it didn't I would like to remove my "hack" to keep the code easier to maintain. 

https://github.com/fable-compiler/fable-browser/blob/ea15afe207b1a41a124de95b028a815ddadf1731/src/Url/Browser.Url.fs#L39-L48

**Comment by lukaszkrzywizna** [comment]
The new version fixed my problem :)

> I assume that this one should be rebuilt.

I've seen the updated code and I meant that if we would like to remove this "hack", we would have to contact the author of that package. Otherwise, no action is needed.

**Comment by MangelMaxime** [comment]
After giving it some thought,

I prefer to have a easy to maintain code and decided to open an issue on https://github.com/Nhowka/Elmish.Bridge/issues/53 to ask the maintainer to publish a new version.

**Comment by MangelMaxime** [comment]
A new version of Elmish.Bridge.Client has been released.

@lukaszkrzywizna Could you please check if everything is working correctly with latest version of Elmish.Bridge.Client now?

**Comment by lukaszkrzywizna** [comment]
I can confirm the newest version of `Elmish.Bridge.Client` and `Fable.Browser.Url` work! Thank you for handling this.
